### ISSUE TITLE
Paste every line from text in clipboard to another layer

### ISSUE THREAD

**Issue by cukabeka** [jbentzen/sketch-fast-text-transfer#1]
I have the issue if I try to populate my design with data from an existing webpage, I need to populate every field manually. It yould come in very handy if the plugin would create a new text layer for every line from the clipboard so I could push them around on the artboard. 
That would be real fast text transfer, too! :)

**Comment by jbentzen** [comment]
Thank you for your feedback. I will keep your request in mind next time I need to update the plugin. I am closing this thread as this is a feature request and not an issue.
